ical-to-google-calendar:
#  users:
#    - id: "user-id"
#      email: "user@email"
#  flows:
#    - user-id: "user-id"
#      i-cal-url: "url-to-feed"
#      google-calendar-name: "google-calendar-name"
#      default-i-cal-time-zone: "Australia/Melbourne"
  authorization-server:
    listening-port: "9889"
    authorization-redirect-url-base: "http://localhost:9889"
  synchronization-schedule-delay: "300000"
  authorization-storage-directory: "/data/storage"
  google-client-secrets-file: "/data/config/client-secret.json"