ical-to-google-calendar:
#  users:
#    - id: "user-id"
#      email: "user@email"
#  flows:
#    - user-id: "user-id"
#      i-cal-url: "url-to-feed"
#      google-calendar-name: "google-calendar-name"
  authorization-server:
    port: "9889"
    host: "localhost"
  synchronization-schedule-delay: "300000"
  google-client-secrets-file: "~/.ical-to-google-calendar/client_secret.json"
  authorization-storage-directory: "~/.ical-to-google-calendar/storage"