ical-to-google-calendar:
#  users:
#    - id: "user-id"
#      email: "user@email"
#  flows:
#    - user-id: "user-id"
#      i-cal-url: "url-to-feed"
#      google-calendar-name: "google-calendar-name"
  authorizationServer:
    port: "9889"
    host: "localhost"
  authorizationStorageDirectory: "~/.ical-to-google-calendar/storage"
  synchronization-schedule-delay: "300000"
  google-client-secrets-file: "~/.ical-to-google-calendar/client_secret.json"